import type { Metadata } from "next";

import "./globals.css";
// import { Bebas_Neue } from "@next/font/google";

// export const bebasNeue = Bebas_Neue({
// 	subsets: ["latin"],
// 	weight: "400",
// });

export const metadata: Metadata = {
  title: "vermaji ka PORTFOLIO",
  description: "Generated by chandan verma",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="text-white">
      <body className="">
        {children}
      </body>
    </html>
  );
}
